# Generated by Django 6.0 on 2026-01-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_id', models.CharField(max_length=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Items.category')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Items_InitialAmount',
            fields=[
                ('initial_amount_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('UOM', models.CharField(max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='initial_amount', to='Items.items')),
            ],
            options={
                'db_table': 'Items_InitialAmount',
            },
        ),
        migrations.CreateModel(
            name='Items_Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('effective_date', models.DateField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='price', to='Items.items')),
            ],
            options={
                'db_table': 'Items_Price',
            },
        ),
        migrations.CreateModel(
            name='Items_Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Items.items')),
            ],
            options={
                'db_table': 'Items_Status',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_type', models.CharField(choices=[('SIN', 'Stock IN'), ('SOU', 'Stock Out'), ('REM', 'Removed'), ('RET', 'Returned')], max_length=3)),
                ('trans_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('approved_on', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='Items.items')),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
    ]
