# Generated by Django 5.2.8 on 2026-01-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='items_price',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.CreateModel(
            name='Items_InitialAmount',
            fields=[
                ('initial_amount_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('UOM', models.CharField(max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='initial_amount', to='Items.items')),
            ],
            options={
                'db_table': 'Items_InitialAmount',
            },
        ),
    ]
