# Generated by Django 6.0 on 2025-12-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasactions',
            new_name='Transactions',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='items_price',
            table='Items_Price',
        ),
        migrations.AlterModelTable(
            name='items_status',
            table='Items_Status',
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='Transactions',
        ),
    ]
