# Generated by Django 5.2.8 on 2026-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_rename_trasactions_transactions_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
